version: '2.1'
services:
    db:      #The postgrase Database Service
        image: postgres:latest
        restart: always
        environment:
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          POSTGRES_DB: postgres
        volumes:
          - db-data3:/var/lib/postgresql/data
        ports:
          - 5432:5432
    zabbix-server:    #The main Zabbix Server Software Service
        image: zabbix/zabbix-server-pgsql:ubuntu-latest
       # host_name: zabbix-server
        restart: always
        environment:
          DB_SERVER_HOST: db
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          POSTGRES_DB: postgres
        ports:
          - 10051:10051
        depends_on:
          - db
    web:
        image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
        restart: always
        environment:
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          POSTGRES_DB: postgres
          ZBX_SERVER_HOST: zabbix-server
          DB_SERVER_HOST: db
          ZBX_POSTMAXSIZE: 64M
          PHP_TZ: "Asia/Yerevan"
          ZBX_MAXEXECUTIONTIME: 5000
        ports:
          - 8090:8080
        depends_on:
          - db
          - zabbix-server
    pgadmin:
       image: dpage/pgadmin4:latest
       environment:
         PGADMIN_DEFAULT_EMAIL: marraz85@gmail.com
         PGADMIN_DEFAULT_PASSWORD: admin
       ports:
         - 8083:80
volumes:
  db-data3:
    driver_opts:
      type: none
      device: /home/marraz85/Dockerproject/data
      o: bind

